<a href="https://colab.research.google.com/github/MinhFus/MachineLearning/blob/main/Buoi1_20130365_DoMinhPhu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1.1

In [ ]:
n = int(input("n = "))
i = 0
List = []
for i in range(n):
  List.append(int(input(str(i)+ " =")))
print(List)
print("Số lớn nhất: "+str(max(List)))
print("Số bé nhất: "+str(min(List)))
sum = 0
for i in List:
  sum = sum + i
print("Tổng: "+str(sum))
List.sort()
# print(L)
positive = 0
nagative = 0
for j in List:
  if j < 0:
    nagative = nagative +1
  elif j > 0:
    positive = positive + 1
print("Số số dương là :  " + str(positive))
print("Số số âm là " + str(nagative))

n = 3
0 =9
1 =-1
2 =3
[9, -1, 3]
Số lớn nhất: 9
Số bé nhất: -1
Tổng: 11
Số số dương là :  2
Số số âm là 1


Task 1.2

In [ ]:
def sn(n):
  sn = 0
  for i in range(n):
    sn += 1/(2*i+1)
  print(sn)
sn(int(input("n = ")))

n = 6
1.878210678210678


Task 1.3

In [ ]:
from IPython.core.display import Math
import datetime as date
from abc import ABC, abstractmethod
import numpy as np
class Product(ABC):
  def __init__(self, name, kind ,price, expiredDate):
    self._name = name
    self._kind = kind
    self._price = price
class ImportedProduct(Product):
  def __init__(self,name, kind ,price, expiredDate, fromCountry):
    super().__init__(name, kind ,price, expiredDate)
    self._fromCountry = fromCountry
class DomesticProduct(Product):
  def __init__(self,name, kind ,price, expiredDate):
    super().__init__(name, kind ,price, expiredDate)
class OderItem:
  def __init__(self, item, amount):
    self.item = item
    self.amount = amount
class Oder:
  def __init__(self, id, customer, employee, date, items):
    self.id = id
    self.customer = customer
    self.employee = employee
    self.date = date
    self.items = items
class OderMananger:
  def __init__(self,oders):
    self.oders = oders
  def _highestPrice(self):
    max = 0
    for oder in self.oders:
      for item in oder.items:
        if item.item._price > max:
          max = item.item._price
    return max
  def _numProductBoughtByType(self,kind):
    count = 0
    for oder in self.oders:
      for item in oder.items:
        if item.item._kind == kind:
          count+= item.amount
    return count
p1 = ImportedProduct('ca phe', 'den', 10000, date.date(2023,5,20),'America')
p2 = ImportedProduct('ca phe', 'sua', 20000, date.date(2023,5,19), 'China')
p3 = DomesticProduct('tra', 'dao', 25000, date.date(2023,5,20))
p4 = DomesticProduct('tra', 'tac', 20000, date.date(2023,5,19))
odi1 = OderItem(p1, 2)
odi2 = OderItem(p2, 3)
odi3 = OderItem(p3, 1)
odi4 = OderItem(p4, 4)
list1 = [odi1, odi2]
list2 = [odi3, odi4]
od1 = Oder('kh1','Do Minh Phu', 'Nguyen Van A', date.date(2023, 2, 20), list1)
od2 = Oder('kh2','Doo Mink Fus', 'Nguyen Van B', date.date(2023, 2, 19), list2)
listoder = [od1, od2]
oderManger = OderMananger(listoder)
print(oderManger._highestPrice())
print(oderManger._numProductBoughtByType('den'))
print(p1._fromCountry)

25000
2
America


Task 2.1

In [ ]:
arr = np.arange(10,26)
arr2 = arr[::-1]
print(arr2)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 2.2

In [ ]:
def _repeat(array):
  n = int(input("n = "))
  arr1 = np.copy(array)
  for i in range(n-1):
    arr2 = np.copy(arr1)
    array = np.concatenate((array,arr2),axis = 0)
  return array
print(_repeat(np.array([1,2,3,4])))

n = 3
[1 2 3 4 1 2 3 4 1 2 3 4]


Task 3.3

In [ ]:
def replace(list):
  for i in range(len(list)):
    for j in range(len(list[i])):
      if list[i,j] > 0.5:
        list[i,j] = 0.5
  print(list)
list = np.array([[ 0.42, 0.48, 0.32],
[ 0.74, 0.58, 0.38],
[ 0.51, 0.34, 0.15 ]])
replace(list)

[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
